### ISSUE TITLE
Could you make your own selfbot

### ISSUE THREAD

**Issue by Daybreak-keks** [RisinPlayZ/spy-selfbot#3]
This is literally Alucard renamed and with some added commands from other selfbots/nukebots.
I request you make your own program, please.

**Comment by Contaigen-II** [comment]
@SPYSBOP.command()
async def ping(ctx, ipp=None):
   await ctx.send(f"pinging {ipp} with 32 bytes of data")
   await ctx.send("Timed out.")

**Comment by RisinPlayZ** [comment]
Read the code before calling skid

**Comment by assault1337** [comment]
skid
